version: '2'
services:
    client:
        build: ./client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/opt/client
    server:
        build: ./server
        ports:
            - "8080:8080"
        volumes:
            - ./server:/opt/server
